"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {createClient} from "@/lib/supabase";
import styles from "./staff.module.css";
type Staff={user_id:string;email:string;role:string;status:string};
export default function StaffPage(){const params=useParams(),slug=typeof params.slug==="string"?params.slug:"",supabase=useMemo(()=>createClient(),[]),[clubId,setClubId]=useState(""),[staff,setStaff]=useState<Staff[]>([]),[state,setState]=useState("Loading staff…"),[busy,setBusy]=useState(false);
const load=useCallback(async()=>{const club=await supabase.from("clubs").select("id").eq("slug",slug).maybeSingle();if(!club.data){setState("Club not found.");return}setClubId(club.data.id);const reply=await supabase.rpc("rallora_list_club_staff",{p_club_id:club.data.id});if(reply.error){setState(reply.error.message);return}setStaff((reply.data??[])as Staff[]);setState("")},[slug,supabase]);useEffect(()=>{void load()},[load]);
async function save(email:string,role:string,status:string){setBusy(true);const reply=await supabase.rpc("rallora_set_club_staff",{p_club_id:clubId,p_email:email,p_role:role,p_status:status});if(reply.error)setState(reply.error.message);else await load();setBusy(false)}
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await save(String(f.get("email")),String(f.get("role")),"active");e.currentTarget.reset()}
return <main className={styles.page}><div className={styles.shell}><header><Link href={`/clubs/${slug}/admin`}>← Club administration</Link><strong>RALLORA · STAFF</strong></header><section className={styles.hero}><span>CLUB ACCESS</span><h1>Organisers and administrators.</h1><p>Add existing Rallora accounts and control who can manage this club.</p></section>{state&&<p className={styles.notice}>{state}</p>}<form className={styles.add} onSubmit={submit}><label>Account email<input name="email" type="email" required placeholder="organiser@example.com"/></label><label>Role<select name="role"><option value="organiser">Organiser</option><option value="admin">Admin</option><option value="owner">Owner</option></select></label><button disabled={busy}>Add staff member</button></form><section className={styles.list}>{staff.map(person=><article key={person.user_id}><div><h2>{person.email}</h2><p>{person.role} · {person.status}</p></div><div><select aria-label={`Role for ${person.email}`} value={person.role} onChange={e=>void save(person.email,e.target.value,person.status)}><option value="organiser">Organiser</option><option value="admin">Admin</option><option value="owner">Owner</option></select><button disabled={busy} onClick={()=>void save(person.email,person.role,person.status==="active"?"suspended":"active")}>{person.status==="active"?"Suspend":"Reactivate"}</button></div></article>)}</section></div></main>}
