"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase";
import RalloraLogo from "@/app/components/rallora-logo";
import styles from "./account.module.css";
export default function AccountPage(){const supabase=useMemo(()=>createClient(),[]),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[signedIn,setSignedIn]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
useEffect(()=>{void supabase.auth.getUser().then(({data})=>{setSignedIn(Boolean(data.user));setEmail(data.user?.email??"")})},[supabase]);
async function reset(e:React.FormEvent){e.preventDefault();setBusy(true);const {error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${window.location.origin}/account`});setMessage(error?.message??"If this account exists, a secure password-reset email has been sent.");setBusy(false)}
async function update(e:React.FormEvent){e.preventDefault();setBusy(true);const {error}=await supabase.auth.updateUser({password});setMessage(error?.message??"Password updated successfully.");if(!error)setPassword("");setBusy(false)}
return <main className={styles.page}><section className={styles.card}><div className={styles.topbar}><Link className={styles.brand} href="/" aria-label="Rallora home"><RalloraLogo variant="light" width={150}/></Link><Link className={styles.returnLink} href="/platform">← Platform admin</Link></div><small>ACCOUNT SECURITY</small><h1>{signedIn?"Security & password":"Reset your password"}</h1><p>{signedIn?`Signed in as ${email}. Use this page when you want to change your Rallora password.`:"Enter your Rallora account email and we’ll send a secure recovery link."}</p>{signedIn?<form onSubmit={update}><label>New password<input type="password" minLength={8} required autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>Update password</button></form>:<form onSubmit={reset}><label>Email<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button disabled={busy}>Send reset email</button></form>}{message&&<p className={styles.message} role="status">{message}</p>}</section></main>}
