"use client";

import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {createClient} from "@/lib/supabase";
import styles from "./events.module.css";

type EventRow={id:string;name:string;format:"americano"|"mexicano"|"custom";status:string;event_date:string;courts:number;rounds:number;points_target:number|null;public_notes:string|null};
type Player={id:string;event_id:string;player_name:string};
type Match={id:string;event_id:string;round_number:number;court_number:number;team_a_player_1:string;team_a_player_2:string;team_b_player_1:string;team_b_player_2:string;team_a_score:number|null;team_b_score:number|null;status:string};

export default function ClubEvents(){
 const params=useParams(),slug=typeof params.slug==="string"?params.slug:"",supabase=useMemo(()=>createClient(),[]);
 const [clubId,setClubId]=useState(""),[clubName,setClubName]=useState(""),[events,setEvents]=useState<EventRow[]>([]),[players,setPlayers]=useState<Player[]>([]),[matches,setMatches]=useState<Match[]>([]),[selected,setSelected]=useState(""),[manager,setManager]=useState(false),[state,setState]=useState("Loading events…"),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const club=await supabase.from("clubs").select("id,name").eq("slug",slug).eq("is_active",true).maybeSingle();if(!club.data){setState("Club not found.");return}setClubId(club.data.id);setClubName(club.data.name);const [{data:{user}},eventReply]=await Promise.all([supabase.auth.getUser(),supabase.from("rallora_club_events").select("id,name,format,status,event_date,courts,rounds,points_target,public_notes").eq("club_id",club.data.id).order("event_date",{ascending:false})]);if(eventReply.error){setState(eventReply.error.message);return}const rows=(eventReply.data??[])as EventRow[];setEvents(rows);const chosen=selected||rows[0]?.id||"";setSelected(chosen);if(user){const [member,platform]=await Promise.all([supabase.from("rallora_club_memberships").select("role,status").eq("club_id",club.data.id).eq("user_id",user.id).eq("status","active").maybeSingle(),supabase.from("rallora_platform_admins").select("user_id").eq("user_id",user.id).maybeSingle()]);setManager(Boolean(platform.data||member.data&&["owner","admin","organiser"].includes(member.data.role)))}if(chosen){const [pr,mr]=await Promise.all([supabase.from("rallora_event_players").select("id,event_id,player_name").eq("event_id",chosen).order("player_name"),supabase.from("rallora_event_matches").select("id,event_id,round_number,court_number,team_a_player_1,team_a_player_2,team_b_player_1,team_b_player_2,team_a_score,team_b_score,status").eq("event_id",chosen).order("round_number").order("court_number")]);if(pr.error||mr.error){setState(pr.error?.message||mr.error?.message||"Could not load event.");return}setPlayers((pr.data??[])as Player[]);setMatches((mr.data??[])as Match[])}else{setPlayers([]);setMatches([])}setState("")},[selected,slug,supabase]);
 useEffect(()=>{void load()},[load]);
 async function createEvent(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget),{data:{user}}=await supabase.auth.getUser();if(!user){setState("Sign in through club administration first.");setBusy(false);return}const reply=await supabase.from("rallora_club_events").insert({club_id:clubId,created_by:user.id,name:String(f.get("name")),format:String(f.get("format")),event_date:String(f.get("date")),courts:Number(f.get("courts")),rounds:Number(f.get("rounds")),points_target:Number(f.get("target"))||null,status:"draft"}).select("id").single();if(reply.error)setState(reply.error.message);else{setSelected(reply.data.id);(e.currentTarget as HTMLFormElement).reset()}setBusy(false);await load()}
 async function addPlayer(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),reply=await supabase.from("rallora_event_players").insert({event_id:selected,player_name:String(f.get("player")).trim()});if(reply.error)setState(reply.error.message);else{e.currentTarget.reset();await load()}}
 async function addMatch(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),ids=["a1","a2","b1","b2"].map(k=>String(f.get(k)));if(new Set(ids).size!==4){setState("Choose four different players.");return}const reply=await supabase.from("rallora_event_matches").insert({event_id:selected,round_number:Number(f.get("round")),court_number:Number(f.get("court")),team_a_player_1:ids[0],team_a_player_2:ids[1],team_b_player_1:ids[2],team_b_player_2:ids[3]});if(reply.error)setState(reply.error.message);else await load()}
 async function saveScore(match:Match,a:string,b:string){const aa=Number(a),bb=Number(b);if(!Number.isInteger(aa)||!Number.isInteger(bb)||aa<0||bb<0){setState("Enter valid non-negative scores.");return}const {data:{user}}=await supabase.auth.getUser(),reply=await supabase.from("rallora_event_matches").update({team_a_score:aa,team_b_score:bb,status:"complete",updated_by:user?.id,updated_at:new Date().toISOString()}).eq("id",match.id);if(reply.error)setState(reply.error.message);else await load()}
 async function publish(status:"published"|"completed"){const reply=await supabase.from("rallora_club_events").update({status,updated_at:new Date().toISOString()}).eq("id",selected);if(reply.error)setState(reply.error.message);else await load()}
 const event=events.find(item=>item.id===selected),names=Object.fromEntries(players.map(p=>[p.id,p.player_name])),table=players.map(player=>{let points=0,played=0;for(const m of matches.filter(x=>x.status==="complete")){const sideA=[m.team_a_player_1,m.team_a_player_2].includes(player.id),sideB=[m.team_b_player_1,m.team_b_player_2].includes(player.id);if(sideA){points+=m.team_a_score??0;played++}if(sideB){points+=m.team_b_score??0;played++}}return{name:player.player_name,points,played}}).sort((a,b)=>b.points-a.points||a.name.localeCompare(b.name));
 return <main className={styles.page}><div className={styles.shell}><header><Link href={`/clubs/${slug}`}>← {clubName||"Club"}</Link><strong>RALLORA · CLUB EVENTS</strong></header><section className={styles.hero}><span>AMERICANO · MEXICANO · CLUB FORMATS</span><h1>More ways to play.</h1><p>Create social competitions, record every court and publish a live Rallora table.</p></section>{state&&<p className={styles.notice}>{state}</p>}{manager&&<form className={styles.create} onSubmit={createEvent}><h2>Create an event</h2><input name="name" required placeholder="Friday Night Americano"/><select name="format"><option value="americano">Americano</option><option value="mexicano">Mexicano</option><option value="custom">Custom</option></select><input name="date" type="date" required/><input name="courts" type="number" min="1" max="50" defaultValue="2"/><input name="rounds" type="number" min="1" max="100" defaultValue="6"/><input name="target" type="number" min="1" max="100" defaultValue="24"/><button disabled={busy}>Create event</button></form>}<nav className={styles.eventNav}>{events.map(item=><button className={item.id===selected?styles.active:""} key={item.id} onClick={()=>setSelected(item.id)}>{item.name}<small>{item.format} · {item.status}</small></button>)}</nav>{event&&<><section className={styles.eventHead}><div><small>{event.format.toUpperCase()} · {new Date(event.event_date).toLocaleDateString("en-GB")}</small><h2>{event.name}</h2><p>{event.rounds} rounds · {event.courts} courts{event.points_target?` · first to ${event.points_target}`:""}</p></div>{manager&&<div><button onClick={()=>void publish("published")}>Publish</button><button onClick={()=>void publish("completed")}>Complete</button></div>}</section>{manager&&<section className={styles.adminGrid}><form onSubmit={addPlayer}><h3>Add player</h3><input name="player" required minLength={2} placeholder="Player name"/><button>Add player</button></form><form onSubmit={addMatch}><h3>Schedule a court</h3><input name="round" type="number" min="1" max="100" placeholder="Round" required/><input name="court" type="number" min="1" max="50" placeholder="Court" required/>{["a1","a2","b1","b2"].map((key,index)=><select name={key} required key={key}><option value="">{index<2?"Team A":"Team B"} player</option>{players.map(p=><option key={p.id} value={p.id}>{p.player_name}</option>)}</select>)}<button disabled={players.length<4}>Add match</button></form></section>}<section className={styles.content}><article><h2>Leaderboard</h2><ol className={styles.table}>{table.map((row,index)=><li key={row.name}><strong>{index+1}</strong><span>{row.name}<small>{row.played} played</small></span><b>{row.points} pts</b></li>)}</ol></article><article><h2>Rounds</h2><div className={styles.matches}>{matches.map(match=><MatchCard key={match.id} match={match} names={names} manager={manager} save={saveScore}/>)}</div></article></section></>}</div></main>;
}

function MatchCard({match,names,manager,save}:{match:Match;names:Record<string,string>;manager:boolean;save:(m:Match,a:string,b:string)=>Promise<void>}){const [a,setA]=useState(match.team_a_score?.toString()??""),[b,setB]=useState(match.team_b_score?.toString()??"");return <div className={styles.match}><small>ROUND {match.round_number} · COURT {match.court_number}</small><p>{names[match.team_a_player_1]} &amp; {names[match.team_a_player_2]}</p><strong>{match.status==="complete"?`${match.team_a_score} – ${match.team_b_score}`:"vs"}</strong><p>{names[match.team_b_player_1]} &amp; {names[match.team_b_player_2]}</p>{manager&&<div><input aria-label="Team A score" value={a} onChange={e=>setA(e.target.value)} inputMode="numeric"/><input aria-label="Team B score" value={b} onChange={e=>setB(e.target.value)} inputMode="numeric"/><button onClick={()=>void save(match,a,b)}>Save</button></div>}</div>}
