"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { createClient } from "@/lib/supabase";
import styles from "../admin.module.css";

type Request = { id:string; season_id:string; team_name:string; captain_name:string; captain_phone:string|null; captain_playtomic_rating:number|null; partner_name:string; partner_email:string|null; partner_playtomic_rating:number|null; partner_invite_id:string|null; status:string; created_at:string };
type Division={id:string;season_id:string;name:string};
export default function RegistrationReviewPage() {
  const params=useParams(); const slug=typeof params.slug === "string" ? params.slug : "";
  const supabase=useMemo(()=>createClient(),[]); const [requests,setRequests]=useState<Request[]>([]); const [divisions,setDivisions]=useState<Division[]>([]); const [selectedDivision,setSelectedDivision]=useState<Record<string,string>>({}); const [state,setState]=useState("Loading…"); const [busy,setBusy]=useState("");
  const load=useCallback(async()=>{setState("Loading…"); const {data:{user}}=await supabase.auth.getUser(); if(!user){setState("Sign in from the club administration page first.");return;}
    const clubReply=await supabase.from("clubs").select("id").eq("slug",slug).maybeSingle(); if(clubReply.error||!clubReply.data){setState("Club not found.");return;}
    const membership=await supabase.from("rallora_club_memberships").select("role,status").eq("club_id",clubReply.data.id).eq("user_id",user.id).maybeSingle(); const platform=await supabase.from("rallora_platform_admins").select("user_id").eq("user_id",user.id).maybeSingle();
    if(!platform.data && (!membership.data || membership.data.status!=="active" || !["owner","admin","organiser"].includes(membership.data.role))){setState("Your account cannot review this club’s registrations.");return;}
    const reply=await supabase.from("rallora_team_applications").select("id,season_id,team_name,captain_name,captain_phone,captain_playtomic_rating,partner_name,partner_email,partner_playtomic_rating,partner_invite_id,status,created_at").eq("club_id",clubReply.data.id).order("created_at",{ascending:false}); if(reply.error){setState(reply.error.message);return;}
    const seasonIds=[...new Set((reply.data??[]).map((item:any)=>item.season_id))];
    const divisionReply=seasonIds.length?await supabase.from("divisions").select("id,season_id,name").in("season_id",seasonIds).order("sort_order"):null;
    if(divisionReply?.error){setState(divisionReply.error.message);return;}
    setDivisions((divisionReply?.data??[]) as Division[]); setRequests((reply.data??[]) as unknown as Request[]);setState(""); },[slug,supabase]);
  useEffect(()=>{if(slug) void load();},[slug,load]);
  const review=async(request:Request,status:"approved"|"declined")=>{const divisionId=selectedDivision[request.id]||null;if(status==="approved"&&!divisionId){setState("Choose a division before approving this team.");return;}setBusy(request.id);const reply=await supabase.rpc("rallora_review_team_application",{p_application_id:request.id,p_decision:status,p_division_id:divisionId});setBusy("");if(reply.error){setState(reply.error.message);return;}await load();};
  return <main className={styles.page}><div className={styles.shell}><header className={styles.nav}><Link href={`/clubs/${slug}/admin`} className={styles.wordmark}>← Club administration</Link></header><section className={styles.hero}><span className={styles.eyebrow}>TEAM REGISTRATION</span><h1>Team applications</h1><p>Review team names, players and current Playtomic ratings. Approval creates the team and gives the applicant captain access.</p></section>{state?<section className={styles.message}><p>{state}</p></section>:<section className={styles.grid}>{requests.map((request)=><article className={styles.card} key={request.id}><span className={styles.status}>{request.status}</span><h3>{request.team_name}</h3><p><strong>Captain:</strong> {request.captain_name}{request.captain_playtomic_rating!=null?` · Playtomic ${request.captain_playtomic_rating}`:""}{request.captain_phone?` · ${request.captain_phone}`:""}</p><p><strong>Partner:</strong> {request.partner_name}{request.partner_playtomic_rating!=null?` · Playtomic ${request.partner_playtomic_rating}`:""}{request.partner_email?` · ${request.partner_email}`:""}</p><p>Submitted {new Date(request.created_at).toLocaleDateString("en-GB")}</p>{request.status==="approved"&&request.partner_invite_id&&<p><strong>Partner invite:</strong> <Link href={`/clubs/${slug}/join-team?invite=${request.partner_invite_id}`}>Open claim link →</Link></p>}{request.status==="pending"&&<><label>Assign division<select value={selectedDivision[request.id]??""} onChange={e=>setSelectedDivision(current=>({...current,[request.id]:e.target.value}))}><option value="">Choose division</option>{divisions.filter(d=>d.season_id===request.season_id).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><div className={styles.actionRow}><button disabled={busy===request.id||!selectedDivision[request.id]} onClick={()=>void review(request,"approved")}>{busy===request.id?"Working…":"Approve & assign division"}</button><button disabled={busy===request.id} onClick={()=>void review(request,"declined")}>Decline</button></div></>}</article>)}{!requests.length&&<article className={styles.card}><h3>No team applications</h3><p>New team registrations will appear here.</p></article>}</section>}</div></main>;
}
