"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { createClient } from "@/lib/supabase";
import styles from "../admin.module.css";

type Request = { id:string; team_name:string; captain_name:string; captain_phone:string|null; captain_playtomic_rating:number|null; partner_name:string; partner_email:string|null; partner_playtomic_rating:number|null; status:string; created_at:string };
export default function RegistrationReviewPage() {
  const params=useParams(); const slug=typeof params.slug === "string" ? params.slug : "";
  const supabase=useMemo(()=>createClient(),[]); const [requests,setRequests]=useState<Request[]>([]); const [state,setState]=useState("Loading…"); const [busy,setBusy]=useState("");
  const load=useCallback(async()=>{setState("Loading…"); const {data:{user}}=await supabase.auth.getUser(); if(!user){setState("Sign in from the club administration page first.");return;}
    const clubReply=await supabase.from("clubs").select("id").eq("slug",slug).maybeSingle(); if(clubReply.error||!clubReply.data){setState("Club not found.");return;}
    const membership=await supabase.from("rallora_club_memberships").select("role,status").eq("club_id",clubReply.data.id).eq("user_id",user.id).maybeSingle(); const platform=await supabase.from("rallora_platform_admins").select("user_id").eq("user_id",user.id).maybeSingle();
    if(!platform.data && (!membership.data || membership.data.status!=="active" || !["owner","admin","organiser"].includes(membership.data.role))){setState("Your account cannot review this club’s registrations.");return;}
    const reply=await supabase.from("rallora_team_applications").select("id,team_name,captain_name,captain_phone,captain_playtomic_rating,partner_name,partner_email,partner_playtomic_rating,status,created_at").eq("club_id",clubReply.data.id).order("created_at",{ascending:false}); if(reply.error){setState(reply.error.message);return;} setRequests((reply.data??[]) as unknown as Request[]);setState(""); },[slug,supabase]);
  useEffect(()=>{if(slug) void load();},[slug,load]);
  const review=async(id:string,status:"approved"|"declined")=>{setBusy(id);const reply=await supabase.rpc("rallora_review_team_application",{p_application_id:id,p_decision:status});setBusy("");if(reply.error){setState(reply.error.message);return;}await load();};
  return <main className={styles.page}><div className={styles.shell}><header className={styles.nav}><Link href={`/clubs/${slug}/admin`} className={styles.wordmark}>← Club administration</Link></header><section className={styles.hero}><span className={styles.eyebrow}>TEAM REGISTRATION</span><h1>Team applications</h1><p>Review team names, players and current Playtomic ratings. Approval creates the team and gives the applicant captain access.</p></section>{state?<section className={styles.message}><p>{state}</p></section>:<section className={styles.grid}>{requests.map((request)=><article className={styles.card} key={request.id}><span className={styles.status}>{request.status}</span><h3>{request.team_name}</h3><p><strong>Captain:</strong> {request.captain_name}{request.captain_playtomic_rating!=null?` · Playtomic ${request.captain_playtomic_rating}`:""}{request.captain_phone?` · ${request.captain_phone}`:""}</p><p><strong>Partner:</strong> {request.partner_name}{request.partner_playtomic_rating!=null?` · Playtomic ${request.partner_playtomic_rating}`:""}{request.partner_email?` · ${request.partner_email}`:""}</p><p>Submitted {new Date(request.created_at).toLocaleDateString("en-GB")}</p>{request.status==="pending"&&<div className={styles.actionRow}><button disabled={busy===request.id} onClick={()=>void review(request.id,"approved")}>{busy===request.id?"Working…":"Approve"}</button><button disabled={busy===request.id} onClick={()=>void review(request.id,"declined")}>Decline</button></div>}</article>)}{!requests.length&&<article className={styles.card}><h3>No team applications</h3><p>New team registrations will appear here.</p></article>}</section>}</div></main>;
}
