"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useParams,useSearchParams} from "next/navigation";
import {createClient} from "@/lib/supabase";
import styles from "./register.module.css";
type Club={id:string;slug:string;name:string;player_registration_terms:string|null};
type Season={id:string;name:string;registration_opens_at:string|null;registration_closes_at:string|null};
export default function RegisterTeamPage(){
 const params=useParams();const searchParams=useSearchParams();const requestedSeasonId=searchParams.get("season")??"";const slug=typeof params.slug==="string"?params.slug:"";const supabase=useMemo(()=>createClient(),[]);
 const [club,setClub]=useState<Club|null>(null),[seasons,setSeasons]=useState<Season[]>([]),[seasonId,setSeasonId]=useState("");
 const season=seasons.find(item=>item.id===seasonId)??null;
 const [userId,setUserId]=useState<string|null>(null),[email,setEmail]=useState(""),[password,setPassword]=useState("");
 const [captainName,setCaptainName]=useState(""),[phone,setPhone]=useState("");
 const [registrationMode,setRegistrationMode]=useState<"pair"|"single"|"standby">("pair"),[preferredLevel,setPreferredLevel]=useState(""),[availability,setAvailability]=useState(""),[futureLeagues,setFutureLeagues]=useState(false);
 const [captainRating,setCaptainRating]=useState(""),[partnerName,setPartnerName]=useState(""),[partnerEmail,setPartnerEmail]=useState(""),[partnerRating,setPartnerRating]=useState("");
 const [existing,setExisting]=useState<string|null>(null),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const [ratingState,setRatingState]=useState<"idle"|"checking"|"synced"|"unmatched"|"unavailable">("idle"),[ratingChecked,setRatingChecked]=useState(false); const [step,setStep]=useState(1);
 const storageKey=`rallora-registration:${slug}:${seasonId||requestedSeasonId||"open"}`;
 useEffect(()=>{let alive=true;(async()=>{const [{data:auth},cr]=await Promise.all([supabase.auth.getUser(),supabase.from("clubs").select("id,slug,name,player_registration_terms").eq("slug",slug).eq("is_active",true).maybeSingle()]);if(!alive)return;setUserId(auth.user?.id??null);if(auth.user?.email)setEmail(auth.user.email);if(!cr.data){setError("This club is unavailable.");return}setClub(cr.data as Club);const now=new Date().toISOString();const sr=await supabase.from("seasons").select("id,name,registration_opens_at,registration_closes_at").eq("club_id",cr.data.id).eq("registration_published",true).order("created_at",{ascending:false});if(sr.error){setError("Could not load this club’s leagues. Please try again.");return}const open=((sr.data??[]) as Season[]).filter(item=>(!item.registration_opens_at||new Date(item.registration_opens_at)<=new Date(now))&&(!item.registration_closes_at||new Date(item.registration_closes_at)>=new Date(now)));setSeasons(open);if(open.length)setSeasonId(open.some(item=>item.id===requestedSeasonId)?requestedSeasonId:open[0].id);if(!open.length){setError("There are no leagues currently open for registration.");return}if(auth.user){const pr=await supabase.from("rallora_player_profiles").select("display_name,phone,playtomic_rating").eq("user_id",auth.user.id).maybeSingle();if(pr.data){setCaptainName(pr.data.display_name??"");setPhone(pr.data.phone??"");if(pr.data.playtomic_rating!=null)setCaptainRating(String(pr.data.playtomic_rating))}}})();return()=>{alive=false}},[slug,supabase,requestedSeasonId]);
 useEffect(()=>{if(!club||!seasonId)return;const raw=sessionStorage.getItem(storageKey);if(!raw)return;try{const saved=JSON.parse(raw);setRegistrationMode(saved.registrationMode??"pair");setCaptainName(saved.captainName??"");setPhone(saved.phone??"");setCaptainRating(saved.captainRating??"");setPartnerName(saved.partnerName??"");setPartnerEmail(saved.partnerEmail??"");setPartnerRating(saved.partnerRating??"");setPreferredLevel(saved.preferredLevel??"");setAvailability(saved.availability??"");setFutureLeagues(Boolean(saved.futureLeagues));setStep(saved.step??1)}catch{}},[club,seasonId,storageKey]);
 useEffect(()=>{if(!club||!seasonId)return;sessionStorage.setItem(storageKey,JSON.stringify({registrationMode,captainName,phone,captainRating,partnerName,partnerEmail,partnerRating,preferredLevel,availability,futureLeagues,step}))},[club,seasonId,storageKey,registrationMode,captainName,phone,captainRating,partnerName,partnerEmail,partnerRating,preferredLevel,availability,futureLeagues,step]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{let uid=userId;if(!uid){const r=await supabase.auth.signUp({email:email.trim(),password,options:{emailRedirectTo:`${window.location.origin}/clubs/${club?.slug??slug}/register?season=${season?.id??seasonId}`}});if(r.error)throw r.error;if(!r.data.user)throw new Error("Could not create your Rallora account.");if(!r.data.session){const signIn=await supabase.auth.signInWithPassword({email:email.trim(),password});if(signIn.error||!signIn.data.user){setMessage("Your account has been created. Confirm your email, then return to this page and sign in to finish registration.");return}uid=signIn.data.user.id}else{uid=r.data.user.id;}setUserId(uid)}if(!club||!season||!uid)throw new Error("Complete the player details.");const profile=await supabase.from("rallora_player_profiles").upsert({user_id:uid,display_name:captainName.trim(),phone:phone.trim()||null,updated_at:new Date().toISOString()});if(profile.error)throw profile.error;if(registrationMode!=="pair"){const r=await supabase.from("rallora_player_pools").upsert({club_id:club.id,season_id:season.id,user_id:uid,pool_type:registrationMode,player_name:captainName.trim(),email:email.trim().toLowerCase(),phone:phone.trim()||null,playtomic_rating:captainRating?Number(captainRating):null,preferred_level:preferredLevel.trim()||null,availability:availability.trim()||null,future_leagues:futureLeagues,status:"available",updated_at:new Date().toISOString()},{onConflict:"season_id,user_id,pool_type"});if(r.error)throw r.error;sessionStorage.removeItem(storageKey);setExisting(registrationMode);setMessage(registrationMode==="single"?"You’re on the looking-for-a-partner list. The club will try to help find a suitable pairing, but a match is not guaranteed.":"You’re on the standby list. The club can contact you if a replacement player is needed.")}else{const r=await supabase.from("rallora_team_applications").insert({club_id:club.id,season_id:season.id,division_id:null,requested_by:uid,team_name:[captainName.trim(),partnerName.trim()].filter(Boolean).join(" / "),captain_name:captainName.trim(),captain_phone:phone.trim()||null,captain_playtomic_rating:captainRating?Number(captainRating):null,partner_name:partnerName.trim(),partner_email:partnerEmail.trim()||null,partner_playtomic_rating:partnerRating?Number(partnerRating):null});if(r.error)throw r.error;sessionStorage.removeItem(storageKey);setExisting("pending");setMessage("Pairing submitted. Your organiser will review it before you go live.")}}catch(x){setError(x instanceof Error?x.message:"Could not submit your team.")}finally{setBusy(false)}}
 return <main className={styles.page}><section className={styles.card}>
 <div className={styles.topNav}><Link href={club?`/clubs/${club.slug}`:"/"} className={styles.back} aria-label="Back to club"><span aria-hidden="true">←</span><span>Back to club</span></Link><span className={styles.eyebrow}>PLAYER REGISTRATION</span></div>
 <div className={styles.progress}><span>Step {step} of 5</span><div>{[1,2,3,4,5].map(n=><i key={n} className={n<=step?styles.progressOn:""}/>)}</div></div>
 <h1>{step===1?(club?`Join a league at ${club.name}`:"Join a league"):step===2?"Create your account":step===3?"About you":step===4?(registrationMode==="pair"?"Your partner":registrationMode==="single"?"Help us find your partner":"Standby availability"):"Review & submit"}</h1>
 <p>{step===1?"Choose how you want to take part. We’ll only ask for what we need.":step===2?"Your Rallora sign-in uses the same email you use for Playtomic.":step===3?"Tell the club who you are. Your Playtomic email is already linked to your account.":step===4?(registrationMode==="pair"?"Add the player you’re entering with. They can claim their own Rallora profile later.":registrationMode==="single"?"Tell the club about your level and availability. They’ll try to find a suitable partner, but a pairing isn’t guaranteed.":"Tell the club when you could step in if another player drops out."):"Check everything looks right before sending your registration."}</p>
 {club?.player_registration_terms&&step===1&&<aside className={styles.terms}><strong>Before you join</strong><p>{club.player_registration_terms}</p></aside>}
 {existing?<div className={styles.applicationState}><strong>{existing==="approved"?"Pairing approved":existing==="single"?"Looking for a partner":existing==="standby"?"Standby list joined":"Application received"}</strong><p>{existing==="approved"?"Your pairing is live. Use the club hub for fixtures and standings.":existing==="single"?"The club can now see you in the singles pool and will try to help create a suitable pairing.":"The club can now see you as an available standby player if a replacement is needed."}</p></div>:
 <form onSubmit={submit}>
  {step===1&&<><div className={styles.choiceGrid}><button type="button" className={registrationMode==="pair"?styles.choiceActive:""} onClick={()=>setRegistrationMode("pair")}><strong>Register a pair</strong><span>I already have a partner</span></button><button type="button" className={registrationMode==="single"?styles.choiceActive:""} onClick={()=>setRegistrationMode("single")}><strong>Register as a single</strong><span>I need help finding a partner</span></button><button type="button" className={registrationMode==="standby"?styles.choiceActive:""} onClick={()=>setRegistrationMode("standby")}><strong>Join standby list</strong><span>I can step in if needed</span></button></div><label>Competition<select required value={seasonId} onChange={e=>setSeasonId(e.target.value)}>{seasons.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><small>{season?.registration_closes_at?`Registration closes ${new Date(season.registration_closes_at).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short"})}`:"Registration is open"}</small></label></>}
  {step===2&&(!userId?<><label>Playtomic email<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><small>This will also be your Rallora sign-in email.</small></label><label>Password<input required type="password" minLength={8} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/><small>Minimum 8 characters.</small></label></>:<aside className={styles.returningPlayer}><strong>Welcome back{captainName?`, ${captainName}`:""}.</strong><p>Your Rallora account is ready, so you can continue with your saved player details.</p></aside>)}
  {step===3&&<div className={styles.player}><div className={styles.playerHead}><strong>You</strong><span>Your details</span></div><label>Full name<input required minLength={2} maxLength={120} value={captainName} onChange={e=>setCaptainName(e.target.value)}/></label><label>Phone <small>(optional)</small><input type="tel" autoComplete="tel" maxLength={40} value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Playtomic email<input type="email" value={email} readOnly/><small>Linked from your Rallora sign-in.</small></label><label>Current Playtomic rating <small>{ratingState==="synced"?"synced":"optional"}</small><input type="number" min="0" max="10" step="0.01" inputMode="decimal" value={captainRating} readOnly={ratingState==="synced"} onChange={e=>setCaptainRating(e.target.value)} placeholder="e.g. 3.42"/></label></div>}
  {step===4&&registrationMode==="pair"&&<div className={styles.player}><div className={styles.playerHead}><strong>Partner</strong><span>Partner invite sent after approval</span></div><label>Full name<input required minLength={2} maxLength={120} value={partnerName} onChange={e=>setPartnerName(e.target.value)}/></label><label>Playtomic email<input required type="email" maxLength={254} value={partnerEmail} onChange={e=>setPartnerEmail(e.target.value)} placeholder="partner@example.com"/></label><label>Current Playtomic rating <small>(optional)</small><input type="number" min="0" max="10" step="0.01" inputMode="decimal" value={partnerRating} onChange={e=>setPartnerRating(e.target.value)} placeholder="e.g. 3.18"/></label></div>}
  {step===4&&registrationMode!=="pair"&&<div className={styles.player}><label>Preferred division / level <small>(optional)</small><input maxLength={120} value={preferredLevel} onChange={e=>setPreferredLevel(e.target.value)} placeholder="e.g. Division 2 / intermediate"/></label><label>Availability <small>(optional)</small><textarea maxLength={500} value={availability} onChange={e=>setAvailability(e.target.value)} placeholder="e.g. Weekday evenings"/></label><label className={styles.check}><input type="checkbox" checked={futureLeagues} onChange={e=>setFutureLeagues(e.target.checked)}/> Keep me available for future leagues too</label></div>}
  {step===5&&<div className={styles.review}><div><span>Competition</span><strong>{season?.name}</strong></div><div><span>Entry</span><strong>{registrationMode==="pair"?"Pair registration":registrationMode==="single"?"Single — looking for a partner":"Standby player"}</strong></div><div><span>You</span><strong>{captainName}</strong><small>{email}</small></div>{registrationMode==="pair"&&<div><span>Partner</span><strong>{partnerName}</strong><small>{partnerEmail}</small></div>}</div>}
  {error&&<p className={styles.error} role="alert">{error}</p>}{message&&<p className={styles.success} role="status">{message}</p>}
  <div className={styles.stepActions}>{step>1&&<button type="button" className={styles.secondary} onClick={()=>{setError("");setStep(step-1)}}>Back</button>}{step<5?<button type="button" onClick={()=>{setError("");if(step===1&&!seasonId)return setError("Choose a competition.");if(step===2&&!userId&&(!email.includes("@")||password.length<8))return setError("Enter a valid email and a password of at least 8 characters.");if(step===3&&captainName.trim().length<2)return setError("Enter your full name.");if(step===4&&registrationMode==="pair"&&(partnerName.trim().length<2||!partnerEmail.includes("@")))return setError("Enter your partner’s name and a valid email.");setStep(step+1)}}>Continue</button>:<button disabled={busy||!season}>{busy?"Submitting…":registrationMode==="single"?"Join partner-finding list":registrationMode==="standby"?"Join standby list":"Submit registration"}</button>}</div>
 </form>}
 </section></main>
}