"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {createClient} from "@/lib/supabase";
import styles from "./register.module.css";
type Club={id:string;slug:string;name:string;player_registration_terms:string|null};
type Season={id:string;name:string;registration_opens_at:string|null;registration_closes_at:string|null};
export default function RegisterTeamPage(){
 const params=useParams();const slug=typeof params.slug==="string"?params.slug:"";const supabase=useMemo(()=>createClient(),[]);
 const [club,setClub]=useState<Club|null>(null),[seasons,setSeasons]=useState<Season[]>([]),[seasonId,setSeasonId]=useState("");
 const season=seasons.find(item=>item.id===seasonId)??null;
 const [userId,setUserId]=useState<string|null>(null),[email,setEmail]=useState(""),[password,setPassword]=useState("");
 const [teamName,setTeamName]=useState(""),[captainName,setCaptainName]=useState(""),[phone,setPhone]=useState("");
 const [captainRating,setCaptainRating]=useState(""),[partnerName,setPartnerName]=useState(""),[partnerEmail,setPartnerEmail]=useState(""),[partnerRating,setPartnerRating]=useState("");
 const [existing,setExisting]=useState<string|null>(null),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const [ratingState,setRatingState]=useState<"idle"|"checking"|"synced"|"unmatched"|"unavailable">("idle"),[ratingChecked,setRatingChecked]=useState(false);
 useEffect(()=>{let alive=true;(async()=>{const [{data:auth},cr]=await Promise.all([supabase.auth.getUser(),supabase.from("clubs").select("id,slug,name,player_registration_terms").eq("slug",slug).eq("is_active",true).maybeSingle()]);if(!alive)return;setUserId(auth.user?.id??null);if(!cr.data){setError("This club is unavailable.");return}setClub(cr.data as Club);const now=new Date().toISOString();const sr=await supabase.from("seasons").select("id,name,registration_opens_at,registration_closes_at").eq("club_id",cr.data.id).eq("status","active").order("created_at",{ascending:false});if(sr.error){setError("Could not load this club’s leagues. Please try again.");return}const open=((sr.data??[]) as Season[]).filter(item=>(!item.registration_opens_at||new Date(item.registration_opens_at)<=new Date(now))&&(!item.registration_closes_at||new Date(item.registration_closes_at)>=new Date(now)));setSeasons(open);if(open.length)setSeasonId(open[0].id);if(!open.length){setError("There are no leagues currently open for registration.");return}if(auth.user){const pr=await supabase.from("rallora_player_profiles").select("display_name,phone,playtomic_rating").eq("user_id",auth.user.id).maybeSingle();if(pr.data){setCaptainName(pr.data.display_name??"");setPhone(pr.data.phone??"");if(pr.data.playtomic_rating!=null)setCaptainRating(String(pr.data.playtomic_rating))}}})();return()=>{alive=false}},[slug,supabase]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{let uid=userId;if(!uid){const r=await supabase.auth.signUp({email:email.trim(),password,options:{emailRedirectTo:window.location.href}});if(r.error)throw r.error;if(!r.data.user||!r.data.session){setMessage("Check your email to confirm your account, then return here to submit your team.");return}uid=r.data.user.id;setUserId(uid)}if(!club||!season||!uid)throw new Error("Complete the team details.");const profile=await supabase.from("rallora_player_profiles").upsert({user_id:uid,display_name:captainName.trim(),phone:phone.trim()||null,updated_at:new Date().toISOString()});if(profile.error)throw profile.error;const r=await supabase.from("rallora_team_applications").insert({club_id:club.id,season_id:season.id,division_id:null,requested_by:uid,team_name:teamName.trim(),captain_name:captainName.trim(),captain_phone:phone.trim()||null,captain_playtomic_rating:captainRating?Number(captainRating):null,partner_name:partnerName.trim(),partner_email:partnerEmail.trim()||null,partner_playtomic_rating:partnerRating?Number(partnerRating):null});if(r.error)throw r.error;setExisting("pending");setMessage("Team submitted. Your organiser will review it before the team goes live.")}catch(x){setError(x instanceof Error?x.message:"Could not submit your team.")}finally{setBusy(false)}}
 return <main className={styles.page}><section className={styles.card}><Link href={club?`/clubs/${club.slug}`:"/"} className={styles.back}>← Back to club</Link><span className={styles.eyebrow}>TEAM REGISTRATION</span><h1>{club?`Join a league at ${club.name}`:"Register your team"}</h1><p>Choose an open league, add your team and submit your entry. Rallora keeps your player profile for future registrations, so returning players won’t need to start from scratch.</p>{club?.player_registration_terms&&<aside className={styles.terms}><strong>Before you join</strong><p>{club.player_registration_terms}</p></aside>}{existing&&<div className={styles.applicationState}><strong>{existing==="approved"?"Team approved":"Application received"}</strong><p>{existing==="approved"?"Your team is live. Use the club hub for fixtures and standings.":"The club organiser will review your team and assign the appropriate division. You do not need to submit again."}</p></div>}<form onSubmit={submit}><div className={styles.step}><span>1</span><div><strong>Choose your league</strong><p>Only leagues currently open for registration are shown.</p></div></div><label>League<select required value={seasonId} onChange={e=>{setSeasonId(e.target.value);setExisting(null)}}>{seasons.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><small>{season?.registration_closes_at?`Registration closes ${new Date(season.registration_closes_at).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short"})}`:"Registration is open"}</small></label>{userId&&<aside className={styles.returningPlayer}><strong>Welcome back{captainName?`, ${captainName}`:""}.</strong><p>Your Rallora player profile has been loaded. Choose a league and we’ll reuse your saved details; you can update them below if anything has changed.</p></aside>}
 {!userId&&<><div className={styles.step}><span>2</span><div><strong>Create your Rallora account</strong><p>This becomes the captain account for the team.</p></div></div><label>Playtomic email<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email linked to your Playtomic account"/><small>Use the email you use for Playtomic. This will also be your Rallora sign-in email.</small></label><label>Password<input required type="password" minLength={8} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label></>}
 <div className={styles.step}><span>{userId?"2":"3"}</span><div><strong>Team details</strong><p>Choose the team name the club will see when reviewing your application.</p></div></div><label>Team name<input required minLength={2} maxLength={120} value={teamName} onChange={e=>setTeamName(e.target.value)} placeholder="e.g. Smash Bros"/></label>
 <div className={styles.player}><div className={styles.playerHead}><strong>Captain</strong><span>Primary club contact</span></div><label>Full name<input required minLength={2} maxLength={120} value={captainName} onChange={e=>setCaptainName(e.target.value)}/></label><label>Phone <small>(optional)</small><input maxLength={40} value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Current Playtomic rating <small>{ratingState==="synced"?"synced from Playtomic":"optional"}</small><input type="number" min="0" max="10" step="0.01" inputMode="decimal" value={captainRating} readOnly={ratingState==="synced"} onChange={e=>setCaptainRating(e.target.value)} placeholder="e.g. 3.42"/></label>{ratingState==="checking"&&<p className={styles.syncNote}>Checking your Playtomic rating…</p>}{ratingState==="synced"&&<p className={styles.syncSuccess}>✓ Rating matched to your Playtomic account.</p>}{ratingState==="unmatched"&&<p className={styles.syncNote}>We could not match this Playtomic email to a player at this club. You can enter your current rating manually.</p>}</div>
 <div className={styles.player}><div className={styles.playerHead}><strong>Partner</strong><span>Invited after approval</span></div><label>Full name<input required minLength={2} maxLength={120} value={partnerName} onChange={e=>setPartnerName(e.target.value)}/></label><label>Playtomic email<input required type="email" maxLength={254} value={partnerEmail} onChange={e=>setPartnerEmail(e.target.value)} placeholder="Email linked to their Playtomic account"/><small>Use your partner’s Playtomic email so their profile and rating can be matched when Playtomic sync is available.</small></label><label>Current Playtomic rating <small>(optional)</small><input type="number" min="0" max="10" step="0.01" inputMode="decimal" value={partnerRating} onChange={e=>setPartnerRating(e.target.value)} placeholder="e.g. 3.18"/></label><p className={styles.syncNote}>If this club has Playtomic connected, your partner can sync their own rating after they claim their Rallora account.</p></div>
 {error&&<p className={styles.error} role="alert">{error}</p>}{message&&<p className={styles.success} role="status">{message}</p>}<button disabled={busy||!season||Boolean(existing)}>{busy?"Submitting…":"Submit team for approval"}</button></form></section></main>
}